version: "3.8"

services:
  nginx:
    image: nginx:1.21.6
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask_app

  flask_app:
    build: .
    expose:
      - 8000
